apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: QW51cmFnMTIzNA==   # base64 of 'Anurag1234'
  DB_NAME: dG9kb19kYg==            # base64 of 'todo_db'
  DB_USER: cm9vdA==               # base64 of 'root'

